// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [

    {
      type: 'doc',
      id: 'intro',
      label: 'intro',
    },

    {
      type: 'category',
      label: 'SSS',

      collapsed: true,

      items: [
        {
          type: 'autogenerated',
          dirName: 'SSS', // 自动扫描 docs/sss 下的所有文档
        },
      ],
    },
    {
      type: 'category',
      label: 'SS',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'SS', // 自动扫描 docs/ss 下的所有文档
        },
      ],
    },
    {
      type: 'category',
      label: 'S',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'S',
        },
      ],
    },
    {
      type: 'category',
      label: 'A+',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'A+',
        },
      ],
    },
    {
      type: 'category',
      label: 'A',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'A',
        },
      ],
    },
    {
      type: 'category',
      label: 'A-',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'A-',
        },
      ],
    },
    {
      type: 'category',
      label: 'B+',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'B+',
        },
      ],
    },
    {
      type: 'category',
      label: 'B',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'B',
        },
      ],
    },
    {
      type: 'category',
      label: 'B-',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'B-',
        },
      ],
    },
    {
      type: 'category',
      label: 'C+',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'C+',
        },
      ],
    },
    {
      type: 'category',
      label: '有用的文档',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'useful_docs',
        },
      ],
    },


  ],
};

export default sidebars;
