export const FIELD_DEFINITIONS = [
  {
    key: 'ugType',
    type: 'select',
    required: true,
    label: { 'zh-Hans': '本科背景', en: 'Undergraduate background' },
    help: { 'zh-Hans': '请选择最贴近的本科院校档次', en: 'Pick the closest tier of your undergrad institution' },
    options: [
      { value: 'us-top', label: { 'zh-Hans': '美本 Top 30', en: 'US top 30' } },
      { value: 'us-mid', label: { 'zh-Hans': '美本 Top 30-100', en: 'US top 30-100' } },
      { value: 'cn-985-top', label: { 'zh-Hans': '清北 / 华5 / 顶尖海外（剑桥、多大等）', en: 'Tsinghua / PKU / Hua-5 / top overseas (Oxbridge, UofT, etc.)' } },
      { value: 'cn-985', label: { 'zh-Hans': '其他 985', en: 'Other Chinese 985' } },
      { value: 'cn-211', label: { 'zh-Hans': '211', en: 'Chinese 211' } },
      { value: 'cn-双非', label: { 'zh-Hans': '双非', en: 'Non-985/211 Chinese university' } },
      { value: 'overseas', label: { 'zh-Hans': '其他海外院校（IIT、台清交、欧洲名校等）', en: 'Other overseas (IIT, NTU/NTHU, European top schools, etc.)' } },
    ],
  },
  {
    key: 'gpaScale',
    type: 'select',
    required: true,
    label: { 'zh-Hans': 'GPA 制式', en: 'GPA scale' },
    help: { 'zh-Hans': '本科成绩单使用的 GPA 制式', en: 'GPA scale used on your transcript' },
    options: [
      { value: '4.0', label: { 'zh-Hans': '4.0 制', en: '4.0 scale' } },
      { value: '4.3', label: { 'zh-Hans': '4.3 制', en: '4.3 scale' } },
      { value: '100', label: { 'zh-Hans': '百分制', en: '100-point scale' } },
      { value: '5.0', label: { 'zh-Hans': '5.0 制（少数欧洲/拉美院校）', en: '5.0 scale (a few European/Latin American schools)' } },
    ],
  },
  {
    key: 'gpa',
    type: 'number',
    required: true,
    label: { 'zh-Hans': 'GPA 数值', en: 'GPA value' },
    help: { 'zh-Hans': '按所选制式填写，如 3.9 / 91.5', en: 'Enter according to the selected scale, e.g. 3.9 or 91.5' },
    min: 0,
    max: 100,
    step: 0.01,
  },
  {
    key: 'major',
    type: 'select',
    required: true,
    label: { 'zh-Hans': '本科专业', en: 'Undergraduate major' },
    options: [
      { value: 'cs', label: { 'zh-Hans': '计算机 / 软件工程', en: 'CS / Software Engineering' } },
      { value: 'ee/ece', label: { 'zh-Hans': 'EE / ECE / 通信', en: 'EE / ECE / Communications' } },
      { value: 'math', label: { 'zh-Hans': '数学 / 统计', en: 'Math / Statistics' } },
      { value: 'physics', label: { 'zh-Hans': '物理', en: 'Physics' } },
      { value: 'other-eng', label: { 'zh-Hans': '其他工科', en: 'Other engineering' } },
      { value: 'other', label: { 'zh-Hans': '其他（含文商科）', en: 'Other (incl. humanities / business)' } },
    ],
  },
  {
    key: 'isCsBackground',
    type: 'boolean',
    required: true,
    label: { 'zh-Hans': '是否科班 CS 背景', en: 'Formal CS coursework background' },
    help: { 'zh-Hans': '是否系统修过 CS 核心课（数据结构、算法、OS、网络等）', en: 'Have you taken core CS courses (DS&Algo, OS, networks, etc.)' },
  },
  {
    key: 'toefl',
    type: 'number',
    required: false,
    label: { 'zh-Hans': '托福总分', en: 'TOEFL total score' },
    help: { 'zh-Hans': '若考过雅思可换算为托福；没考可留空', en: 'If you took IELTS, convert to TOEFL equivalent; leave blank if not taken' },
    min: 0,
    max: 120,
    step: 1,
  },
  {
    key: 'gre',
    type: 'group',
    required: false,
    label: { 'zh-Hans': 'GRE 成绩（若有）', en: 'GRE scores (if any)' },
    help: { 'zh-Hans': '没有 GRE 可整组留空', en: 'Leave the entire group blank if no GRE' },
    fields: [
      { key: 'total', type: 'number', label: { 'zh-Hans': '总分', en: 'Total' }, min: 260, max: 340 },
      { key: 'q', type: 'number', label: { 'zh-Hans': 'Quant', en: 'Quant' }, min: 130, max: 170 },
      { key: 'v', type: 'number', label: { 'zh-Hans': 'Verbal', en: 'Verbal' }, min: 130, max: 170 },
      { key: 'aw', type: 'number', label: { 'zh-Hans': 'AW', en: 'AW' }, min: 0, max: 6, step: 0.5 },
    ],
  },
  {
    key: 'research',
    type: 'select',
    required: true,
    label: { 'zh-Hans': '科研产出', en: 'Research output' },
    options: [
      { value: 'none', label: { 'zh-Hans': '无（或只有未发表的 RA 经历）', en: 'None (or unpublished RA experience only)' } },
      { value: 'domestic-paper', label: { 'zh-Hans': '国内期刊 / 普通会议论文', en: 'Domestic journal / mid-tier conference paper' } },
      { value: 'top-conf-coauthor', label: { 'zh-Hans': '顶会 / 顶刊合作 / 非一作', en: 'Top-tier conference/journal co-author' } },
      { value: 'top-conf-first', label: { 'zh-Hans': '顶会 / 顶刊一作', en: 'Top-tier conference/journal first author' } },
    ],
  },
  {
    key: 'internships',
    type: 'number',
    required: true,
    label: { 'zh-Hans': '实习段数', en: 'Number of internships' },
    help: { 'zh-Hans': '累计有几段独立的实习经历', en: 'Total count of distinct internship stints' },
    min: 0,
    max: 20,
    step: 1,
  },
  {
    key: 'bigTechIntern',
    type: 'boolean',
    required: true,
    label: { 'zh-Hans': '是否有大厂 / 顶级量化实习', en: 'Big tech or top quant internship?' },
    help: { 'zh-Hans': 'FAANG / 字节 / 阿里 / 腾讯 / 微软 / Nvidia / 顶级量化', en: 'FAANG / ByteDance / Alibaba / Tencent / Microsoft / Nvidia / top quant' },
  },
  {
    key: 'strongRecs',
    type: 'number',
    required: true,
    label: { 'zh-Hans': '强推数量', en: 'Number of strong recommendations' },
    help: { 'zh-Hans': '海外大牛 / 业内大佬 / 顶级教授的强推', en: 'From famous overseas faculty / industry leaders / top professors' },
    min: 0,
    max: 5,
    step: 1,
  },
  {
    key: 'targetTrack',
    type: 'select',
    required: true,
    label: { 'zh-Hans': '目标方向', en: 'Target track' },
    options: [
      { value: 'cs-general', label: { 'zh-Hans': 'CS 综合（SDE 方向）', en: 'General CS / SDE-oriented' } },
      { value: 'ml-ai', label: { 'zh-Hans': 'ML / AI', en: 'ML / AI' } },
      { value: 'systems', label: { 'zh-Hans': '系统 / 底层', en: 'Systems / low-level' } },
      { value: 'ds', label: { 'zh-Hans': 'Data Science / 数据科学', en: 'Data Science' } },
      { value: 'ece-hw', label: { 'zh-Hans': 'ECE 硬件 / 芯片', en: 'ECE hardware / chip' } },
      { value: 'ee-signal', label: { 'zh-Hans': 'EE 信号 / 通信', en: 'EE signal / communications' } },
      { value: 'flexible', label: { 'zh-Hans': '都可以 / 还在探索', en: 'Flexible / still exploring' } },
    ],
  },
  {
    key: 'needScholarship',
    type: 'boolean',
    required: true,
    label: { 'zh-Hans': '是否强需要奖学金 / 低学费', en: 'Need scholarship or low tuition?' },
    help: { 'zh-Hans': '是否对项目成本敏感（影响推荐 list 的偏好）', en: 'Whether tuition is a hard constraint (affects recommendations)' },
  },
  {
    key: 'locationPref',
    type: 'select',
    required: true,
    label: { 'zh-Hans': '地理位置偏好', en: 'Location preference' },
    options: [
      { value: 'flexible', label: { 'zh-Hans': '无所谓', en: 'No preference' } },
      { value: 'east-coast', label: { 'zh-Hans': '东岸', en: 'East coast' } },
      { value: 'west-coast', label: { 'zh-Hans': '西岸', en: 'West coast' } },
      { value: 'midwest', label: { 'zh-Hans': '中部', en: 'Midwest' } },
      { value: 'south', label: { 'zh-Hans': '南部', en: 'South' } },
      { value: 'no-rural', label: { 'zh-Hans': '不接受乡村小镇', en: 'No rural college towns' } },
    ],
  },
];
