// `showIf(profile)` — 可选条件函数，返回 false 时前端不渲染该字段
//   profile 是当前表单状态对象（含其他字段当前值）。
// `isCsBackground` 由 `major === 'cs'` 派生（不再作为独立 boolean 字段）。

export const FIELD_DEFINITIONS = [
  {
    key: 'ugType',
    type: 'select',
    required: true,
    label: { 'zh-Hans': '本科背景', en: 'Undergraduate background' },
    help: { 'zh-Hans': '请选择最贴近的本科院校档次', en: 'Pick the closest tier of your undergrad institution' },
    options: [
      { value: 'us-top', label: { 'zh-Hans': '美本 Top 30', en: 'US top 30' } },
      { value: 'us-mid', label: { 'zh-Hans': '美本 Top 30-100', en: 'US top 30-100' } },
      { value: 'cn-transfer-us', label: { 'zh-Hans': '陆本转学美本（2+2 / 3+1 等）', en: 'CN→US transfer (2+2 / 3+1)' } },
      { value: 'cn-joint-venture', label: { 'zh-Hans': '中外合办（XJTLU / 宁诺 / 上海 NYU / 昆山杜克等）', en: 'Sino-foreign joint venture (XJTLU / UNNC / NYU Shanghai etc.)' } },
      { value: 'overseas-top', label: { 'zh-Hans': '顶尖海外（牛津 / 剑桥 / 帝国 / ETH / 多伦多 / 港三所等）', en: 'Top overseas (Oxford / Cambridge / Imperial / ETH / UofT / HKU·HKUST·CUHK, etc.)' } },
      { value: 'cn-tsinghua-pku', label: { 'zh-Hans': '清北', en: 'Tsinghua / Peking' } },
      { value: 'cn-sustech-shtech', label: { 'zh-Hans': '上科大 / 南科大', en: 'ShanghaiTech / SUSTech' } },
      { value: 'cn-hua5', label: { 'zh-Hans': '华5（复旦 / 交大 / 浙大 / 中科大 / 哈工大）', en: 'Hua-5 (Fudan / SJTU / ZJU / USTC / HIT)' } },
      { value: 'cn-985', label: { 'zh-Hans': '其他 985', en: 'Other Chinese 985' } },
      { value: 'cn-211', label: { 'zh-Hans': '211', en: 'Chinese 211' } },
      { value: 'cn-双非', label: { 'zh-Hans': '双非', en: 'Non-985/211 Chinese university' } },
      { value: 'overseas', label: { 'zh-Hans': '其他海外院校（IIT / 香港城市 / 港理工 / NTU·NTHU / 欧洲非顶尖等）', en: 'Other overseas (IIT / CityU·HK / PolyU·HK / NTU·NTHU / European non-top, etc.)' } },
    ],
  },
  {
    key: 'gpaScale',
    type: 'select',
    required: true,
    label: { 'zh-Hans': 'GPA 制式', en: 'GPA scale' },
    options: [
      { value: '4.0', label: { 'zh-Hans': '4.0 制', en: '4.0 scale' } },
      { value: '4.3', label: { 'zh-Hans': '4.3 制', en: '4.3 scale' } },
      { value: '100', label: { 'zh-Hans': '百分制', en: '100-point scale' } },
      { value: '5.0', label: { 'zh-Hans': '5.0 制（少数欧洲/拉美院校）', en: '5.0 scale (a few European/Latin American schools)' } },
    ],
  },
  {
    key: 'gpa',
    type: 'number',
    required: true,
    label: { 'zh-Hans': 'GPA', en: 'GPA' },
    min: 0, max: 100, step: 0.01,
  },
  {
    key: 'jointForeignGpa',
    type: 'number',
    required: false,
    label: { 'zh-Hans': '海外段 GPA', en: 'Foreign-portion GPA' },
    help: { 'zh-Hans': '中外合办 / 转学美本的海外段 GPA', en: 'GPA of the overseas portion (joint venture or US transfer)' },
    min: 0, max: 100, step: 0.01,
    showIf: (p) => p && (p.ugType === 'cn-joint-venture' || p.ugType === 'cn-transfer-us'),
  },
  {
    key: 'jointForeignGpaScale',
    type: 'select',
    required: false,
    label: { 'zh-Hans': '海外段 GPA 制式', en: 'Foreign-portion GPA scale' },
    options: [
      { value: '4.0', label: { 'zh-Hans': '4.0 制', en: '4.0 scale' } },
      { value: '4.3', label: { 'zh-Hans': '4.3 制', en: '4.3 scale' } },
      { value: '100', label: { 'zh-Hans': '百分制', en: '100-point scale' } },
    ],
    showIf: (p) => p && (p.ugType === 'cn-joint-venture' || p.ugType === 'cn-transfer-us'),
  },
  {
    key: 'major',
    type: 'select',
    required: true,
    label: { 'zh-Hans': '本科专业', en: 'Undergraduate major' },
    help: { 'zh-Hans': '选「计算机 / 软件工程」会按科班 CS 评估，其余都按转码处理', en: 'Selecting "CS / SE" is treated as formal CS; everything else is non-CS / transition.' },
    options: [
      { value: 'cs', label: { 'zh-Hans': '计算机 / 软件工程', en: 'CS / Software Engineering' } },
      { value: 'ee/ece', label: { 'zh-Hans': 'EE / ECE / 通信', en: 'EE / ECE / Communications' } },
      { value: 'math', label: { 'zh-Hans': '数学 / 统计', en: 'Math / Statistics' } },
      { value: 'physics', label: { 'zh-Hans': '物理', en: 'Physics' } },
      { value: 'other-eng', label: { 'zh-Hans': '其他工科', en: 'Other engineering' } },
      { value: 'other', label: { 'zh-Hans': '其他（含文商科）', en: 'Other (incl. humanities / business)' } },
    ],
  },
  {
    key: 'csCoursesCompleted',
    type: 'number',
    required: false,
    label: { 'zh-Hans': '已修 CS 核心课程数', en: 'CS core courses completed' },
    help: { 'zh-Hans': '数据结构 / 算法 / 操作系统 / 数据库 / 网络 等核心课', en: 'DS&A / OS / DB / Networks core courses' },
    min: 0, max: 20, step: 1,
    showIf: (p) => p && p.major !== 'cs',
  },
  {
    key: 'csCoursesTakenCount',
    type: 'number',
    required: false,
    label: { 'zh-Hans': '已修 CS 课程总数', en: 'Total CS courses taken' },
    min: 0, max: 50, step: 1,
    showIf: (p) => p && p.major !== 'cs',
  },
  {
    key: 'toefl',
    type: 'number',
    required: false,
    label: { 'zh-Hans': '托福分数', en: 'TOEFL score' },
    help: { 'zh-Hans': '新版 1-6 或旧版 0-120 均可，留空则按未考', en: 'New 1-6 band or old 0-120; leave blank if not taken' },
    min: 0, max: 120, step: 0.5,
  },
  {
    key: 'ielts',
    type: 'number',
    required: false,
    label: { 'zh-Hans': '雅思总分', en: 'IELTS overall' },
    min: 0, max: 9, step: 0.5,
  },
  {
    key: 'hasGre',
    type: 'boolean',
    required: false,
    label: { 'zh-Hans': '是否有 GRE 成绩', en: 'Have GRE scores?' },
  },
  {
    key: 'gre',
    type: 'group',
    required: false,
    label: { 'zh-Hans': 'GRE 成绩', en: 'GRE scores' },
    fields: [
      { key: 'total', type: 'number', label: { 'zh-Hans': '总分', en: 'Total' }, min: 260, max: 340 },
      { key: 'q', type: 'number', label: { 'zh-Hans': 'Quant', en: 'Quant' }, min: 130, max: 170 },
      { key: 'v', type: 'number', label: { 'zh-Hans': 'Verbal', en: 'Verbal' }, min: 130, max: 170 },
      { key: 'aw', type: 'number', label: { 'zh-Hans': 'AW', en: 'AW' }, min: 0, max: 6, step: 0.5 },
    ],
    showIf: (p) => p && p.hasGre === true,
  },
  {
    key: 'research',
    type: 'select',
    required: true,
    label: { 'zh-Hans': '科研产出', en: 'Research output' },
    options: [
      { value: 'none', label: { 'zh-Hans': '无科研经历', en: 'No research experience' } },
      { value: 'ra-no-output', label: { 'zh-Hans': '有科研经历但无产出（RA / 暑研未 publish）', en: 'Research experience but no publication (RA / summer)' } },
      { value: 'domestic-paper', label: { 'zh-Hans': '国内期刊 / 普通会议论文', en: 'Domestic journal / mid-tier conference paper' } },
      { value: 'top-conf-coauthor', label: { 'zh-Hans': '顶会论文合作 / 非一作（CVPR / ICCV / NeurIPS 等）', en: 'Top-tier conference paper, co-author (CVPR / ICCV / NeurIPS etc.)' } },
      { value: 'top-conf-first', label: { 'zh-Hans': '顶会论文一作（CVPR / ICCV / NeurIPS 等）', en: 'Top-tier conference paper, first author' } },
    ],
  },
  {
    key: 'internships',
    type: 'number',
    required: true,
    label: { 'zh-Hans': '实习段数', en: 'Number of internships' },
    min: 0, max: 20, step: 1,
  },
  {
    key: 'bigTechIntern',
    type: 'boolean',
    required: true,
    label: { 'zh-Hans': '是否有大厂 / 顶级量化实习', en: 'Big tech or top quant internship?' },
  },
  {
    key: 'hasFullTime',
    type: 'boolean',
    required: true,
    label: { 'zh-Hans': '是否有全职工作经历（≥1 年）', en: 'Full-time work experience (≥1 year)?' },
  },
  {
    key: 'strongRecs',
    type: 'select',
    required: true,
    label: { 'zh-Hans': '强推情况', en: 'Strong recommendations' },
    help: { 'zh-Hans': '海外大牛 / 业内大佬 / 顶级教授的强推', en: 'From famous overseas faculty / industry leaders / top professors' },
    options: [
      { value: 'unknown', label: { 'zh-Hans': '不确定', en: 'Not sure' } },
      { value: '1', label: { 'zh-Hans': '1 段强推', en: '1 strong rec' } },
      { value: '2', label: { 'zh-Hans': '2 段强推', en: '2 strong recs' } },
      { value: '3', label: { 'zh-Hans': '3 段及以上', en: '3 or more' } },
    ],
  },
  {
    key: 'targetTrack',
    type: 'select',
    required: true,
    label: { 'zh-Hans': '目标方向', en: 'Target track' },
    options: [
      { value: 'cs-general', label: { 'zh-Hans': 'CS 综合（SDE 方向）', en: 'General CS / SDE-oriented' } },
      { value: 'ml-ai', label: { 'zh-Hans': 'ML / AI', en: 'ML / AI' } },
      { value: 'systems', label: { 'zh-Hans': '系统 / 底层', en: 'Systems / low-level' } },
      { value: 'ds', label: { 'zh-Hans': 'Data Science / 数据科学', en: 'Data Science' } },
      { value: 'ece-hw', label: { 'zh-Hans': 'ECE 硬件 / 芯片', en: 'ECE hardware / chip' } },
      { value: 'ee-signal', label: { 'zh-Hans': 'EE 信号 / 通信', en: 'EE signal / communications' } },
      { value: 'flexible', label: { 'zh-Hans': '都可以 / 还在探索', en: 'Flexible / still exploring' } },
    ],
  },
  {
    key: 'careerGoal',
    type: 'select',
    required: true,
    label: { 'zh-Hans': '毕业后的目标', en: 'Career goal after graduation' },
    help: { 'zh-Hans': '选「美国读博」时结果页会额外推荐适合读博 / 转博的项目', en: 'If "PhD in the US", the result page shows extra PhD-friendly recs.' },
    options: [
      { value: 'us-job', label: { 'zh-Hans': '美国找工', en: 'Work in the US' } },
      { value: 'cn-job', label: { 'zh-Hans': '回国找工', en: 'Work in China' } },
      { value: 'us-phd', label: { 'zh-Hans': '美国读博', en: 'PhD in the US' } },
      { value: 'unsure', label: { 'zh-Hans': '还不确定', en: 'Not sure yet' } },
    ],
  },
];
